- name: Install nginx
  ansible.builtin.apt:
    name: 
      - nginx
      - prometheus-nginx-exporter
    state: present
- name: Copy file default and restart nginx
  ansible.builtin.copy:
    src: default
    dest: /etc/nginx/sites-enabled/default
  notify:
    Restart nginx
- service:
    enabled: yes
    name: "{{ item }}"
    state: started
  loop:
    - nginx
    - prometheus-nginx-exporter
    