- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
- name: Copy file default and restart nginx
  ansible.builtin.copy:
    src: default
    dest: /etc/nginx/sites-enabled/default
  notify:
    Restart nginx
- name: nginx service is running
  service:
    name: nginx
    state: started
    enabled: true
