- name: Create a directory if it does not exists /etc/nginx/sites-enabled
  file:
    path: /etc/nginx/sites-enabled
    state: 'directory'
- name: Copy file default and restart nginx
  ansible.builtin.copy:
    src: default
    dest: /etc/nginx/sites-enabled/default
- name: Install nginx
  ansible.builtin.apt:
    name: 
      - nginx
      - prometheus-nginx-exporter
    state: present
- service:
    enabled: yes
    name: "{{ item }}"
    state: started
  loop:
    - nginx
    - prometheus-nginx-exporter
    