---
- name: Grafana directory
  file:
    path: /opt/grafana
    state: 'directory'
- name: Configurate grafana
  template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
  no_log: true
  notify: 
    - Restart grafana
- name: Configurate provisioning
  file:
    path: "/opt/grafana/provisioning/{{ item }}"
    state: directory
  loop:
    - datasources
    - dashboards

- name: Configurate provisioning
  copy:
    src: "{{item }}"
    dest: "/opt/grafana/provisioning/{{ item }}"
  loop:
    - datasources/default.yaml
    - dashboards/main.json
    - dashboards/syslog.json
    - dashboards/mysql.json
    - dashboards/default.yaml
  notify:
    Restart grafana

# - block:
#   - name: Configurate datasources
#     copy:
#       src: datasources.yaml
#       dest: /opt/grafana/provisioning/datasources/default.yaml
#   - name: Configurate dashboards
#     copy:
#       src: main.json
#       dest: /opt/grafana/dashboards/
#   - name: Configurate dashboard syslog
#     copy:
#       src: syslog.json
#       dest: /opt/grafana/dashboards/
#   - name: Configurate dashboard mysql
#     copy:
#       src: mysql.json
#       dest: /opt/grafana/dashboards/
#   - name: Configurate dashboards provising
#     copy:
#       src: default.yaml
#       dest: /opt/grafana/provisioning/dashboards/
  # notify: 
  #   - Restart grafana-server

- name: Grafana Docker container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana
    published_ports: "{{ grafana_port }}:3000"
    volumes: 
      - /opt/grafana:/etc/grafana