- name: Install uwsgi
  apt:
    name: 
      - uwsgi
      - uwsgi-plugin-python3
    state: present
- name: Copy file agama.ini with owner and permission and restart uwsgi
  template:
    src: agama.ini.j2
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    group: agama
    mode: '0600'
  no_log: true
  notify:
    Restart uwsgi
- name: uWSGI service is running
  service:
    name: uwsgi
    state: started
    enabled: true
