apiVersion: 1
providers:
  - name: Prometheus
    allowUiUpdates: true
    disableDeletion: false
    updateIntervalSeconds: 10
    options:
      path: /var/lib/grafana/dashboards/
      foldersFromFilesStructure: true