apiVersion: 1
providers:
  - name: default
    allowUiUpdates: true
    disableDeletion: false
    updateIntervalSeconds: 10
    options:
      path: /etc/grafana/provisioning/dashboards
      foldersFromFilesStructure: true

