{
 "title": "Main dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Instances status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "bind9 {{ instance }}" },
    { "expr": "mysql_up", "legendFormat": "mysql {{ instance }}" },
    { "expr": "nginx_up", "legendFormat": "nginx {{ instance }}" }
   ]
  },
  {
   "title": "Amount of A DNS queries per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "bind_resolver_queries_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "haproxy server up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_server_up", "legendFormat": "{{ instance }}" },
    {
     "expr": "haproxy_server_up{server=\"docker2\"}",
     "legendFormat": "docker2 {{ instance }}"
    }
   ]
  },
  {
   "title": "keepalived_vrrp_state ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{instance=\"timofeimih-1:9165\"}",
     "legendFormat": "timofeimih-1"
    },
    {
     "expr": "keepalived_vrrp_state{instance=\"timofeimih-2:9165\"}",
     "legendFormat": "timofeimih-2"
    }
   ]
  },
  {
   "title": "haproxy up",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "haproxy_up{instance=\"timofeimih-1:9188\"}",
     "legendFormat": "timofeimih-1 haproxy"
    },
    {
     "expr": "haproxy_up{instance=\"timofeimih-2:9188\"}",
     "legendFormat": "timofeimih-2 haproxy"
    }
   ]
  },
  {
   "title": "InfluxDB health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success",
     "legendFormat": "Status"
    },
    { "expr": "influxdb_write_write_ok", "legendFormat": "InfluxDB write rate" }
   ]
  },
  {
   "title": "Memory consumption on VMs",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Amount of selects per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "mysql_global_status_commands_total",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Amount of requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "targets": [
    { "expr": "nginx_http_requests_total", "legendFormat": "{{ instance }}" }
   ]
  }
 ]
}