{
 "title": "MySQL",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Instances status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "MySQL server ids ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "mysql_slave_status_slave_sql_running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_sql_running",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "MySQL server read only status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "MySQL replication threads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "mysql_slave_status_slave_io_running ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Amount of selects per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "mysql_global_status_commands_total",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}