- name: Create a directory if it does not exists /opt/agama
  file:
    path: /opt/agama
    state: 'directory'
- name: Download agama.py and Dockerfile
  get_url:
    url: "{{ item }}"
    dest: /opt/agama
  loop:
    - https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    - https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile
- name: Build Docker image
  community.docker.docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama

- name: Docker volume
  community.docker.docker_volume:
    name: "{{ item.name }}"
  loop: "{{ containers }}"
- name: Agama Docker container start
  community.docker.docker_container:
    name: "{{ item.name }}"
    image: agama
    published_ports: "{{ item.port }}:8000"
    env:
      AGAMA_DATABASE_URI=mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}
  no_log: True
  loop: "{{ containers }}"

- include_role:
    name: dns_record
  vars:
    dns_record: "www{{ inventory_hostname.replace(machine_name, '') }}"