{
 "title": "Main dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Instances status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bind_up{instance=\"timofeimih-2:9119\"}",
     "legendFormat": "Bind9"
    },
    { "expr": "mysql_up", "legendFormat": "MySQL" },
    {
     "expr": "nginx_up{instance=\"timofeimih-1:9113\"}",
     "legendFormat": "Nginx timofeimih-1"
    },
    {
     "expr": "nginx_up{instance=\"timofeimih-2:9113\"}",
     "legendFormat": "Nginx timofeimih-2"
    }
   ]
  },
  {
   "title": "keepalived_vrrp_state ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{instance=\"timofeimih-1:9165\"}",
     "legendFormat": "timofeimih-1"
    },
    {
     "expr": "keepalived_vrrp_state{instance=\"timofeimih-2:9165\"}",
     "legendFormat": "timofeimih-2"
    }
   ]
  },
  {
   "title": "Amount of A DNS queries per minute",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "bind_resolver_queries_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "haproxy server up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{server=\"docker1\"}",
     "legendFormat": "docker1"
    },
    {
     "expr": "haproxy_server_up{server=\"docker2\"}",
     "legendFormat": "docker2"
    }
   ]
  },
  {
   "title": "Memory consumption on VMs",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "haproxy up",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_up{instance=\"timofeimih-1:9188\"}",
     "legendFormat": "timofeimih-1 haproxy"
    },
    {
     "expr": "haproxy_up{instance=\"timofeimih-2:9188\"}",
     "legendFormat": "timofeimih-2 haproxy"
    }
   ]
  },
  {
   "title": "InfluxDB health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success",
     "legendFormat": "Status"
    },
    { "expr": "influxdb_write_write_ok", "legendFormat": "InfluxDB write rate" }
   ]
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"idle\"}[1m]) * -1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Amount of requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "targets": [
    { "expr": "nginx_http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Amount of selects per minute",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "mysql_global_status_commands_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}