{
 "title": "MySQL",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "mysql_slave_status_slave_sql_running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_sql_running{instance=\"timofeimih-1:9104\"}",
     "legendFormat": "timofeimih-1"
    },
    {
     "expr": "mysql_slave_status_slave_sql_running{instance=\"timofeimih-2:9104\"}",
     "legendFormat": "timofeimih-2"
    }
   ]
  },
  {
   "title": "MySQL server read only status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only{instance=\"timofeimih-1:9104\"}",
     "legendFormat": "timofeimih-1"
    },
    {
     "expr": "mysql_global_variables_read_only{instance=\"timofeimih-2:9104\"}",
     "legendFormat": "timofeimih-2"
    }
   ]
  },
  {
   "title": "mysql_slave_status_slave_io_running ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running{instance=\"timofeimih-1:9104\"}",
     "legendFormat": "timofeimih-1"
    },
    {
     "expr": "mysql_slave_status_slave_io_running{instance=\"timofeimih-2:9104\"}",
     "legendFormat": "timofeimih-2"
    }
   ]
  },
  {
   "title": "MySQL replication threads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running{instance=\"timofeimih-1:9104\"}",
     "legendFormat": "timofeimih-1"
    },
    {
     "expr": "mysql_slave_status_slave_sql_running{instance=\"timofeimih-2:9104\"}",
     "legendFormat": "timofeimih-2"
    }
   ]
  },
  {
   "title": "Instances status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "MySQL server ids ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Amount of selects per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "mysql_global_status_commands_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}