- name: Install bind9
  apt:
    name: bind9
    state: present
- block:
    - name: Create a directory if it does not exists /var/cache/bind
      file:
        path: /var/cache/bind
        state: 'directory'
    - name: Copy file named.conf.options and restart bind9
      template:
        src: named.conf.options.j2
        dest: /etc/bind/named.conf.options
    - name: Copy file named.conf.local and restart bind9
      template:
        src: named.conf.local.j2
        dest: /etc/bind/named.conf.local
    - stat: path=/var/cache/bind/db.{{ startup_name }}
      register: db_uploaded
    - stat: path=/var/cache/bind/db.{{ startup_name }}
      register: db_rev_uploaded  
    - name: Copy file db.{{ startup_name }}, restart bind9 and RNDC reload
      template:
        src: db.{{ startup_name }}.j2
        dest: /var/cache/bind/db.{{ startup_name }}
      when: db_uploaded is not defined
    - name: Copy file db.rev, restart bind9 and RNDC reload
      template:
        src: db.rev.j2
        dest: /var/cache/bind/db.rev
      when: db_rev_uploaded is not defined
  notify: 
    - Restart bind9
    - RNDC reload


- name: Display all variables/facts known for a host
  debug:
    msg: "{{ db_uploaded is not defined }}"


# - name: Install prometheus-bind-exporter
#   apt:
#     name: prometheus-bind-exporter
#     state: present

- service:
    enabled: yes
    name: "{{ item }}"
    state: started
  loop:
    - bind9
    - prometheus-bind-exporter

- name: Add or modify ansible.example.org A to 192.168.1.1"
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ dns_update_key }}"
    server: "{{ groups['dns_primary'][0] }}"
    zone: "{{ startup_name }}"
    record: "backup"
    value: "{{ backup_server_ip }}"
  when: inventory_hostname == groups['dns_primary'][0]

