- name: Restart keepalived
  service:
    name: keepalived
    state: restarted
- name: Restart keepalived-exporter
  systemd:
    name: keepalived-exporter
    state: restarted
    daemon_reload: true

