- name: Add or modify backup A"
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ dns_update_key }}"
    server: "{{ groups['dns_primary'][0] }}"
    zone: "{{ startup_name }}"
    record: "backup"
    value: "{{ backup_server_ip }}"
- name: "Add or modify ns-1 CNAME groups['dns_servers']"
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ dns_update_key }}"
    server: "{{ groups['dns_primary'][0] }}"
    zone: "{{ startup_name }}"
    type: "CNAME"
    record: "ns-{{ i+1 }}"
    value: "{{ item  }}"
  loop: "{{ groups['dns_servers']  }}"
  loop_control:
    index_var: i