
- name: Copy file .my.cnf and restart MySQL
  template: 
    src: .my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
    owner: prometheus
    group: prometheus
    mode: '0600'
  notify:
    Restart prometheus-mysqld-exporter
- name: Install MySQL-server
  apt:
    name: mysql-server
    state: present
- name: Install python3-pymysql
  apt:
    name: python3-pymysql
    state: present
- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
- name: Copy file override.cnf and restart MySQL
  copy:
    src: override.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify:
    Restart mysql
- name: MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
- name: Create MySQL user dedicated for exporter
  community.mysql.mysql_user:
    name: "{{ mysql_exporter_login }}"
    password: "{{ mysql_exporter_password }}"
    host: "localhost"
    priv: "*.*:SELECT,GRANT,REPLICATION CLIENT"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true
- name: Install prometheus-mysqld-exporter
  apt:
    name: prometheus-mysqld-exporter
    state: present

- service:
    enabled: yes
    name: "{{ item }}"
    state: started
  loop:
    - mysql
    - prometheus-mysqld-exporter

- name: Create a directory if it does not exists /home/backup/mysql
  file:
    path: /home/backup/mysql
    state: 'directory'
    owner: backup
    group: backup

- name: MySQL user
  community.mysql.mysql_user:
    name: "{{ backup_login }}"
    password: "{{ backup_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:LOCK TABLES, SELECT"
    login_unix_socket: /var/run/mysqld/mysqld.sock
- name: Copy file .my.cnf to /home/backup
  template: 
    src: backup.my.cnf.j2
    dest: /home/backup/.my.cnf
    owner: backup
    group: backup
    mode: '0600'
- name: Copy file mysql-backup
  template: 
    src: mysql-backup.j2
    dest: /etc/cron.d/mysql-backup