---
- name: Systemd daemon_reload telegraf
  systemd:
    name: telegraf
    state: restarted
    daemon_reload: true
- name: Restart prometheus-influxdb-stats-exporter
  service:
    name: prometheus-influxdb-stats-exporter
    state: restarted
- name: Restart telegraf
  service:
    name: telegraf
    state: restarted
- name: Restart influxdb
  service:
    name: influxdb
    state: restarted
