- name: Install prometheus
  apt:
    name: prometheus
    state: present
- name: Copy file prometheus.yml
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify:
    Restart prometheus
- name: Copy file prometheus
  template:
    src: prometheus.j2
    dest: /etc/default/prometheus
  notify:
    Restart prometheus


- service:
    enabled: true
    name: prometheus
    state: started

- include_role:
    name: dns_record
  vars:
    dns_record: prometheus