- name: Install bind9
  apt:
    name: bind9
    state: present
- name: Copy file named.conf.options and restart bind9
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: 
    Restart bind9
- name: Copy file named.conf.local and restart bind9
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: 
    Restart bind9
- name: Copy file db.{{ startup_name }}, restart bind9 and RNDC reload
  template:
    src: db.{{ startup_name }}.j2
    dest: /etc/bind/db.{{ startup_name }}
  notify: 
    - Restart bind9
    - RNDC reload
- name: Install prometheus-bind-exporter
  apt:
    name: prometheus-bind-exporter
    state: present

- service:
    enabled: yes
    name: "{{ item }}"
    state: started
  loop:
    - bind9
    - prometheus-bind-exporter
    
# - name: run setup
#   setup:
# - name: Display all variables/facts known for a host
#   debug:
#     msg: "{{ hostvars['timofeimih-1'] }}"