- name: Ansible ping module
  ping:
- name: Add user 'juri'
  user:
    name: juri
- name: Add user 'roman'
  user:
    name: roman
- name: Set authorized keys taken from url for juri
  ansible.posix.authorized_key:
    user: juri
    state: present
    key: https://github.com/hudolejev.keys
    path: /home/juri/.ssh/.authorized_key
- name: Set authorized keys taken from url for roman
  ansible.posix.authorized_key:
    user: roman
    state: present
    key: https://github.com/roman.keys
    path: /home/roman/.ssh/.authorized_key
- name: Update APT cache
  apt:
    cache_valid_time: 86400
- name: Install Prometheus-node-exporter
  apt:
    name: prometheus-node-exporter
    state: present
- name: Service is prometheus-node-exporter running
  service:
    name: prometheus-node-exporter
    state: started
    enabled: true

- name: Install ca-certificates
  apt:
    name: ca-certificates>=20230311ubuntu0.20.04.1
    state: present

- name: Configurate rsyslog
  copy:
    src: 50-telegraf.conf
    dest: /etc/rsyslog.d/
  notify:
    - Restart rsyslog