# - name: Ansible ping module
#   ansible.builtin.ping:
- name: Add user 'juri'
  ansible.builtin.user:
    name: juri
- name: Add user 'roman'
  ansible.builtin.user:
    name: roman
- name: Set authorized keys taken from url for juri
  ansible.posix.authorized_key:
    user: juri
    state: present
    key: https://github.com/hudolejev.keys
    path: /home/juri/.ssh/.authorized_key
- name: Set authorized keys taken from url for roman
  ansible.posix.authorized_key:
    user: roman
    state: present
    key: https://github.com/roman.keys
    path: /home/roman/.ssh/.authorized_key
- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400