- name: Ansible ping module
  ping:
- name: Create user 'juri'
  user:
    name: juri
- name: Create user 'roman'
  user:
    name: roman
- name: Set authorized keys taken from url for juri
  ansible.posix.authorized_key:
    user: juri
    state: present
    key: https://github.com/hudolejev.keys
    path: /home/juri/.ssh/.authorized_key
- name: Set authorized keys taken from url for roman
  ansible.posix.authorized_key:
    user: roman
    state: present
    key: https://github.com/roman.keys
    path: /home/roman/.ssh/.authorized_key
- name: Update APT cache
  apt:
    cache_valid_time: 86400
- name: Install Prometheus-node-exporter
  apt:
    name: prometheus-node-exporter
    state: present
- name: Service is prometheus-node-exporter running
  service:
    name: prometheus-node-exporter
    state: started
    enabled: true

- name: Install ca-certificates
  apt:
    name: ca-certificates>=20230311ubuntu0.20.04.1
    state: present

- name: Configurate rsyslog
  template:
    src: 50-telegraf.conf.j2
    dest: /etc/rsyslog.d/50-telegraf.conf
  notify:
    - Restart rsyslog

- name: Create user 'backup'
  user:
    name: backup
    create_home: true
    home: /home/backup
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa

- name: Copy known_hosts
  template:
    src: known_hosts.j2
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    group: backup

- name: Create a directory if it does not exists /home/backup/restore
  file:
    path: /home/backup/restore
    state: 'directory'
    owner: backup
    group: backup

- name: Install duplicity
  apt:
    name: duplicity
    state: present
