apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    orgId: 1
    access: proxy
    uid: Prometheus-1
    url: http://prometheus:9090/prometheus/
    editable: true
  - name: Pinger
    type: influxdb
    access: proxy
    uid: Pinger
    url: http://influxdb:8086
    editable: true
    jsonData:
      dbName: pinger
  - name: Telegraf
    type: influxdb
    access: proxy
    uid: Telegraf
    url: http://influxdb:8086
    editable: true
    jsonData:
      dbName: telegraf

